#!/bin/bash
#
# Used by the 'jenkins-packerbuilds' repo

#######################################
# Used to determine fill-in configurations for 
# the template file used by HashiCorp's Packer.
# Globals:
#   PROGRAM_NAME
#   build_name
#   GUEST_OS_TYPE
#   OS_BUILD_CONF_NAME
#   ISO_FILE
#   iso_checksum
#   ISO_IMAGES_PATH
#   SHELL_PROVISIONER_NAME
#   SHELL_PROVISIONERS_CONFIG_FILE_NAME
#   PACKER_TEMPLATE_NAME
#   JENKINS_GITHUB_CREDENTIAL_SECRET
# Outputs:
#   - the previous template but with _PLACEHOLDER(s) evaluated
#######################################
evaluservars () {
    TEMP_FILE_NAME="${PROGRAM_NAME}-temp"
    # check jq documentation, inspired from:
    # https://stackoverflow.com/questions/53670702/jq-error-test1-0-is-not-defined-at-top-level-line-1#answer-53674099
    # shellcheck disable=2154
    jq < "$PACKER_TEMPLATE_NAME" --arg BUILD_NAME "$build_name" --arg GUEST_OS_TYPE "$GUEST_OS_TYPE" \
     --arg OS_BUILD_CONF_NAME "$OS_BUILD_CONF_NAME" --arg ISO_FILE "$ISO_FILE" --arg ISO_CHECKSUM "$iso_checksum" \
     --arg ISO_IMAGES_PATH "file://$ISO_IMAGES_PATH" --arg SHELL_PROVISIONER_NAME "$SHELL_PROVISIONER_NAME" \
     --arg SHELL_PROVISIONERS_CONFIG_FILE_NAME "$SHELL_PROVISIONERS_CONFIG_FILE_NAME" \
     --arg JENKINS_GITHUB_CREDENTIAL_SECRET "$JENKINS_GITHUB_CREDENTIAL_SECRET" \
     '. *= (
        { variables: 
            {
            "vm_name": $BUILD_NAME,
            "ssh_user": "reap2sow1",
            "ssh_pass": "Passw0rd!",
            "shutdown_command": "sudo -S shutdown -h now",
            "guest_os_type": $GUEST_OS_TYPE,
            "os_build_conf": $OS_BUILD_CONF_NAME,
            "iso_file_name": $ISO_FILE,
            "iso_file_hash": $ISO_CHECKSUM,
            "iso_url_local_parent_directory": $ISO_IMAGES_PATH,
            "shell_provisioner": $SHELL_PROVISIONER_NAME,
            "shell_provisioners_config_file_name": $SHELL_PROVISIONERS_CONFIG_FILE_NAME,
            "github_secret": $JENKINS_GITHUB_CREDENTIAL_SECRET
            }
        }
    )' > "$TEMP_FILE_NAME"
    mv "$TEMP_FILE_NAME" "$PACKER_TEMPLATE_NAME"
}
